name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.3.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfbdd7c0c4eca36ea87d50371d6899d5ef668371afb923cc8b0f04ed3126535b"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
