name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.2.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23e989163d05a795541c5f885de03d6851f3756d7dcdafee318831c541b65b78"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
