name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "038ff1656e04b005eb5526b55dfd5a547b9a3226929661a1c78377f5a1ddac24"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
