name = "Vanilla+"
author = "PostPoetic"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26ee93ffcdf2171d62dfa9221cb5a9501a6b31c665122bea9776b4b40853074e"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
