name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9413c41d59c3386ff42193e37ad7bf44387cf89e854cff30c1315f9136aa64dd"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
