name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "607d819dc49241f21e18fff4640dd946ca667db288943c6ec18783d0ee8cf3ed"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
