name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.0.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e34e101bfc1256fe1d96de2aaa6dde1c3656d8c6edca1bead88682450c8f1249"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
