name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "471ea78472547fa775ab6c92914c8f692af396e946291c574af5456135b5c505"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
