name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2caf7a08182749e7af912180a17e0c90e6949d4b2a00755d591255a23bdc0809"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
