name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "42435e5012cb6f385e001d212bc3478f24f075fa3a5947d2508a1656b07676f5"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
