name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.3.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5f9d2f5fca55fe7c7eb7166ede64630d7c57f1a95b9aaa6ae5fbff50023cfb0"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
