name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2370f8eeec22bfcd83f9588e02795123046f8c02539d3dc064d6893b2f73b7b"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
