name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "df5580cc460d90fe6dda0d28e8b78cda197de2b923f2fe620a57bfad1ee0ca46"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
