name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4730f4b279dd84c39610734427b65073058210719c74c4e088950e53d440bb9a"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
