name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.2.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a88d9cf232048d92f6f1fb00b3edc784c8430c2ac1d4c1dbac891cda415c780"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
