name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7c7b547d691adcbdfdcfca88cc21f8000c340047223e76d14ae0d135559ed008"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
