name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b16f86dfe426ed9614c42f7cdc88e939a067689b64083f260a3bed572023f8"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
