name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.3.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c34ef1af5405b5b767cbc588d535e9ada585bcab94a474e9f1751c5089ea804"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
