name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddf854fb7f6ac86c6bc0eb928ef64871da895d2314efeeccd790845ce40b7092"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
