name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afdbc0ff81552c0c93dc26e409da3cb930d43f63da8cfcfdac8e67ead8f60ee2"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
