name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63f809d410ea93302833a74fe232478a75e6afdd98a5c55eb802d27987f479b6"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
