name = "DietWeezeStuck"
author = "PostPoetic"
version = "1.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "319836372a87a7d8c8adc8bf235d3d76473652b392e935d0bee98fbebf79be3c"

[versions]
fabric = "0.13.3"
minecraft = "1.18.2"
